#테스트에서만 유효한 것
#git? ?????? ??? base-addi? ????.
#??
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/app10_test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
#??? value ??? ? ? ??