#git에 올리면 안되는 것
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: [NEED]
            clientSecret: [NEED]
            scope: read:user, user:email
          kakao:
            clientId: [NEED]
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
test:
  username: 1234
